name: Deploy Frontend (Dev)

on:
  push:
    branches:
      - develop
  repository_dispatch:
    types: [infra_updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        # Uses the variable synced by your Terraform repo
        run: aws s3 sync dist/ s3://${{ vars.S3_BUCKET_NAME }} --delete
      - name: Wait for CloudFront
        run: sleep 180

      - name: Invalidate CloudFront
        # Uses the secret synced by your Terraform repo
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"